-- One-time company profile update for Thennaiyan Coconut Company.
-- Run this in Supabase SQL editor if an existing site_settings row still has old placeholder data.

alter table public.site_settings
  add column if not exists registration_type text not null default 'Regular GST Registration',
  add column if not exists gst_valid_from text not null default '22/01/2026',
  add column if not exists gst_valid_to text not null default 'Not Applicable (Active Registration)',
  add column if not exists proprietor_designation text not null default 'Proprietor',
  add column if not exists proprietor_state text not null default 'Tamil Nadu',
  add column if not exists gst_approving_officer text not null default 'Assistant Commissioner',
  add column if not exists gst_certificate_issue_date text not null default '22/01/2026',
  add column if not exists additional_branches text not null default '0 (No additional registered business locations)';

insert into public.site_settings (
  id,
  business_name,
  brand_short,
  whatsapp_number,
  contact_phone,
  contact_email,
  business_hours,
  legal_owner,
  gst_number,
  business_type,
  registration_type,
  gst_reg_date,
  gst_valid_from,
  gst_valid_to,
  jurisdiction,
  proprietor_designation,
  proprietor_state,
  gst_approving_officer,
  gst_certificate_issue_date,
  additional_branches,
  address
) values (
  true,
  'Thennaiyan Coconut Company',
  'Thennaiyan',
  '918124165047',
  '+91 81241 65047',
  'support@thennaiyan.in',
  'Monday - Saturday: 08:00 AM - 06:00 PM IST',
  'Tamilarasan Sathuragiri',
  '33RRKPS2222A1ZU',
  'Proprietorship (Single Owner Business)',
  'Regular GST Registration',
  '22 January 2026',
  '22/01/2026',
  'Not Applicable (Active Registration)',
  'Thirumangalam',
  'Proprietor',
  'Tamil Nadu',
  'Assistant Commissioner',
  '22/01/2026',
  '0 (No additional registered business locations)',
  'No. 265/3B, Veppampatti Vilakku, Peraiyur Main Road Near Bus Stop, Pappinaickanpatti, Peraiyur, Madurai District, Tamil Nadu - 625705, India'
)
on conflict (id) do update set
  business_name = excluded.business_name,
  brand_short = excluded.brand_short,
  whatsapp_number = excluded.whatsapp_number,
  contact_phone = excluded.contact_phone,
  contact_email = excluded.contact_email,
  business_hours = excluded.business_hours,
  legal_owner = excluded.legal_owner,
  gst_number = excluded.gst_number,
  business_type = excluded.business_type,
  registration_type = excluded.registration_type,
  gst_reg_date = excluded.gst_reg_date,
  gst_valid_from = excluded.gst_valid_from,
  gst_valid_to = excluded.gst_valid_to,
  jurisdiction = excluded.jurisdiction,
  proprietor_designation = excluded.proprietor_designation,
  proprietor_state = excluded.proprietor_state,
  gst_approving_officer = excluded.gst_approving_officer,
  gst_certificate_issue_date = excluded.gst_certificate_issue_date,
  additional_branches = excluded.additional_branches,
  address = excluded.address;
